# Generated by Django 5.2.1 on 2025-06-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_profile_email_remove_profile_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="kevin", max_length=200)),
                ("password", models.CharField(default="asdasd24", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="GuestCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="andrey", max_length=200)),
                ("password", models.CharField(default="asdasd", max_length=200)),
            ],
        ),
    ]
