# Generated by Django 5.2.1 on 2025-06-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20250601_1856"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, help_text="Beschreibung oder Bio"),
        ),
        migrations.AddField(
            model_name="profile",
            name="file",
            field=models.ImageField(
                blank=True,
                help_text="Profilbild.",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Adresse oder Standort", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tel",
            field=models.CharField(
                blank=True,
                help_text="Telefonnummer z.B. +49 123 4567 890",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="working_hours",
            field=models.IntegerField(default=0, help_text="Arbeitsstunden"),
        ),
    ]
