# Generated by Django 5.2.1 on 2025-06-02 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="business_user",
            field=models.ForeignKey(
                limit_choices_to={"type": "business"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_business",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_user",
            field=models.ForeignKey(
                limit_choices_to={"type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="revisions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="in_progress",
                max_length=15,
            ),
        ),
    ]
