# Generated by Django 5.2.1 on 2025-06-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0007_offer_revisions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="revisions",
        ),
        migrations.AddField(
            model_name="offerdetail",
            name="business_user",
            field=models.ForeignKey(
                limit_choices_to={"type": "business"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
