# Generated by Django 5.2.1 on 2025-06-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0008_remove_offer_revisions_offerdetail_business_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_time_in_days",
        ),
        migrations.RemoveField(
            model_name="order",
            name="features",
        ),
        migrations.RemoveField(
            model_name="order",
            name="offer_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="revisions",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="title",
        ),
        migrations.AddField(
            model_name="order",
            name="offer_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_detail",
                to="marktplace.offerdetail",
            ),
        ),
    ]
