# Generated by Django 5.2.1 on 2025-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0012_remove_order_delivery_time_in_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="offer_detail_id",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time_in_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="order",
            name="offer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="revisions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
