# Generated by Django 5.2.1 on 2025-06-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0014_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="offer_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_details",
                to="marktplace.offerdetail",
            ),
        ),
    ]
