# Generated by Django 5.2.1 on 2025-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marktplace", "0016_alter_order_business_user_alter_order_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="customer_user",
        ),
        migrations.AddField(
            model_name="offer",
            name="min_delivery_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="min_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
