# Generated by Django 5.2.1 on 2025-06-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marktplace", "0018_offer_user_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="min_price",
        ),
    ]
