# Generated by Django 5.2.1 on 2025-06-17 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0009_remove_order_delivery_time_in_days_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="offer_detail",
            new_name="offer_detail_id",
        ),
    ]
