# Generated by Django 5.2.1 on 2025-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0013_remove_order_offer_detail_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="in_progress",
                max_length=100,
            ),
        ),
    ]
