# Generated by Django 5.2.1 on 2025-06-19 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0015_order_offer_detail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="business_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "business"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_business",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "customer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
