# Generated by Django 5.2.1 on 2025-06-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marktplace", "0019_remove_offer_min_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="min_delivery_time",
        ),
    ]
