# Generated by Django 5.2.1 on 2025-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerdetail",
            name="delivery_time_in_days",
            field=models.IntegerField(null=True),
        ),
    ]
