# Generated by Django 5.2.1 on 2025-06-09 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="comment",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="review",
            name="business_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "business"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
