# Generated by Django 5.2.1 on 2025-07-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        help_text="Profilbild.",
                        null=True,
                        upload_to="profile_pictures/",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Adresse oder Standort", max_length=255
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        help_text="Telefonnummer z.B. +49 123 4567 890",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Beschreibung oder Bio"),
                ),
                ("working_hours", models.CharField(help_text="Arbeitsstunden")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
