# Generated by Django 5.2.1 on 2025-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_created_at_profile_description_profile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="working_hours",
            field=models.CharField(help_text="Arbeitsstunden"),
        ),
    ]
