# Generated by Django 5.2.1 on 2025-06-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marktplace", "0006_offerdetail"),
        (
            "reviews",
            "0002_rename_comment_review_description_remove_review_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer",
                to="marktplace.offer",
            ),
        ),
    ]
