# Generated by Django 5.2.1 on 2025-06-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_review_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
    ]
