# Generated by Django 5.2.1 on 2025-06-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_remove_review_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "customer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
